if: repo != head_repo

_reference_os: &reference_os
  linux

_reference_arch: &reference_arch
  amd64

_reference_jdk: &reference_jdk
  JDK="adopt@1.11"

language: minimal

git:
  depth: false
  autocrlf: input

os:
  - *reference_os
  - osx
  - windows

dist: focal

arch:
  - *reference_arch
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
    - secure: "g/xBTxOU7AOj7DaOEn+NU7kz4MDOib2gyA8FGjRSurGqd7LqdudI4Dw+dnpUV8oFxSda59iiGUbrwgv9xMWUQWtJFdL/oPOBYx9PFJNxQgLBexf7xu+ZLZxoMi1sxQo+1oa9zWIOhPNv4fCZLwf805X6pFj5ucx8XJoP5lEweYqyyt0eBa+Xtd8MndG3KieSSeeGKZFhBF6KXwcd1k5nM0Job84SItNjrhogg4EXQQBnv+MOkAq3ZeJaotPcO+EJzU/OU7jh/F6o4GwYwioVGDbTqqp4eCYfO82LIymzQa+tRIvgzQe8BmFtZrfTKuQ/+0GfU9LV5VpQJfVeSTP+hrhEd4uuBAJ/JqpZKW2WRJQC/mSr3Hu+iywOrFh04dBhlXwsdVx7u4px4Lj+rPPjathVm5ioVdFu4Nnyio0s0DeglDBpBqggY9HQpILj3VjV4dykehELB91Dz1MXVzR0F8mKHVJPlmxHk+i7XXX6yEcPJOUzUsYP24vmxKE8xQfLiIxt9a2gjrlquzUsTI0X1aTeXHZPahzCVQkm1pt7gN4h0UQbud5wikK9vH69arKYUxzdFPQY8yk5stlrGxA4gRNyjPaEP/lC26MLhoISdvMOZp4a4CbmiY3G25OwFRSY/p3TwDelLuRLNwOshL6dhzKEs2u1farrQUoN11rbgE0="
  matrix:
    - *reference_jdk
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

stages:
  - Compile
  - Kotlin Style Check
  - Check
  - name: test
    if: 'commit_message !~ /\[\s*skip(?: |-|\.)test\s*\].*/'
  - name: Delievry
    if: repo = maciabit/deleteme-lss

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk

_workspace_name: &workspace_name
  compiled_env

_import_workspace: &import_workspace
  worskapces:
    use: *workspace_name

jobs:
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: Compile
      script: travis_retry ./gradlew compileKotlin --parallel
      workspaces:
        create:
          name: *workspace_name
          paths:
            - "$TRAVIS_BUILD_DIR"
            - "$HOME/.gradle"
    - <<: *reference_machine
      stage: Kotlin Style Check
      <<: *import_workspace
      script: travis_retry ./gradlew detekt ktlintCheck --parallel
    - <<: *reference_machine
      stage: Complete Check
      <<: *import_workspace
      script:
        - travis_retry ./gradlew check
    - stage: Delivery
      script: "true"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  true

script:
  - travis_retry ./gradlew test